apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproj2-deployment
spec:
  replicas: 2
    template:
    metadata:
      labels:
        app: capstoneproj2-deployment
    spec:
      containers:
      - name: capstoneproj2-deployment
        image: dockergijju/capstoneproject2
        ports:
        - containerPort: 80
