apiVersion: v1
kind: Service
metadata:
  name: capstoneproj2-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: capstoneproj2-deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
